# Generated by Django 4.2.30 on 2026-09-10 03:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('ANALYSING', 'ANALYSING'), ('READY_FOR_REVIEW', 'READY_FOR_REVIEW'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], db_index=True, default='RECEIVED', max_length=32)),
                ('analysis_result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work Item',
                'verbose_name_plural': 'Work Items',
                'db_table': 'work_items',
                'ordering': ['-created_at'],
            },
        ),
    ]
